stages:
  - ver
  - build
  - review
  - stage
  - prod

cache:
  paths:
    - node_modules/

ver:
  stage: ver
  script:
    - whoami
    - node -v
    - npm -v
  tags:
    - zwzt-static

build:
  stage: build
  script:
    - npm install
    - npm run generate
  artifacts:
    paths:
      - dist
    expire_in: 1 hour
  tags:
    - zwzt-static

review:
  stage: review
  script:
    - rsync -av --delete dist /srv/nginx/$CI_PROJECT_NAME/$CI_BUILD_REF_SLUG
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://$CI_BUILD_REF_SLUG.$CI_PROJECT_NAME.$APPS_DOMAIN
    on_stop: stop_review
  only:
    - branches
  except:
    - master
  tags:
    - zwzt-static

stop_review:
  stage: review
  script:
    - rm -rf dist /srv/nginx/$CI_PROJECT_NAME/$CI_BUILD_REF_SLUG
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  tags:
    - zwzt-static

staging:
  stage: stage
  script:
    - rsync -av --delete dist /srv/nginx/$CI_PROJECT_NAME/stage
  environment:
    name: stage
    url: http://stage.$CI_PROJECT_NAME.$APPS_DOMAIN
  only:
    - master
  tags:
    - zwzt-static

prod:
  stage: prod
  script:
    - rsync -av --delete dist /srv/nginx/$CI_PROJECT_NAME/prod
  environment:
    name: prod
    url: http://prod.$CI_PROJECT_NAME.$APPS_DOMAIN
  when: manual
  only:
    - master
  tags:
    - zwzt-static
